CREATE TABLE results
(
    id             BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    user_id        DOUBLE PRECISION                        NOT NULL,
    x_coord        DOUBLE PRECISION                        NOT NULL,
    y_coord        DOUBLE PRECISION                        NOT NULL,
    radius         DOUBLE PRECISION                        NOT NULL,
    hit_result     BOOLEAN                                 NOT NULL,
    created_at     TIMESTAMP WITHOUT TIME ZONE             NOT NULL,
    execution_time BIGINT,
    CONSTRAINT pk_results PRIMARY KEY (id)
);